// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: friends_001.sql

package database

import (
	"context"
	"database/sql"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friend_requests
SET status = 'accepted', updated_at = now()
WHERE id = ?
`

func (q *Queries) AcceptFriendRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, acceptFriendRequest, id)
	return err
}

const addFriend = `-- name: AddFriend :exec
INSERT INTO friends (user_id, friend_id)
VALUES (?, ?)
`

type AddFriendParams struct {
	UserID   sql.NullString
	FriendID sql.NullString
}

func (q *Queries) AddFriend(ctx context.Context, arg AddFriendParams) error {
	_, err := q.db.ExecContext(ctx, addFriend, arg.UserID, arg.FriendID)
	return err
}

const checkFriendRequestExists = `-- name: CheckFriendRequestExists :one
SELECT COUNT(*)
FROM friend_requests
WHERE (from_user = ? AND to_user = ?) OR (from_user = ? AND to_user = ?)
`

type CheckFriendRequestExistsParams struct {
	FromUser   sql.NullString
	ToUser     sql.NullString
	FromUser_2 sql.NullString
	ToUser_2   sql.NullString
}

func (q *Queries) CheckFriendRequestExists(ctx context.Context, arg CheckFriendRequestExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkFriendRequestExists,
		arg.FromUser,
		arg.ToUser,
		arg.FromUser_2,
		arg.ToUser_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkFriendRequestExistsWithID = `-- name: CheckFriendRequestExistsWithID :one
SELECT COUNT(*) 
FROM friend_requests
WHERE id = ?
`

func (q *Queries) CheckFriendRequestExistsWithID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkFriendRequestExistsWithID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const declineFriendRequest = `-- name: DeclineFriendRequest :exec
UPDATE friend_requests
SET status = 'declined', updated_at = now()
WHERE id = ?
`

func (q *Queries) DeclineFriendRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, declineFriendRequest, id)
	return err
}

const deleteFriend = `-- name: DeleteFriend :exec
DELETE FROM friends
WHERE (user_id = ? AND friend_id = ?) OR (user_id = ? AND friend_id = ?)
`

type DeleteFriendParams struct {
	UserID     sql.NullString
	FriendID   sql.NullString
	UserID_2   sql.NullString
	FriendID_2 sql.NullString
}

func (q *Queries) DeleteFriend(ctx context.Context, arg DeleteFriendParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriend,
		arg.UserID,
		arg.FriendID,
		arg.UserID_2,
		arg.FriendID_2,
	)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM friend_requests
WHERE id = ?
`

func (q *Queries) DeleteFriendRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequest, id)
	return err
}

const getFriendID = `-- name: GetFriendID :one
SELECT user_id
FROM friends
WHERE (user_id = ? AND friend_id = ?) OR (user_id = ? AND friend_id = ?)
LIMIT 1
`

type GetFriendIDParams struct {
	UserID     sql.NullString
	FriendID   sql.NullString
	UserID_2   sql.NullString
	FriendID_2 sql.NullString
}

func (q *Queries) GetFriendID(ctx context.Context, arg GetFriendIDParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getFriendID,
		arg.UserID,
		arg.FriendID,
		arg.UserID_2,
		arg.FriendID_2,
	)
	var user_id sql.NullString
	err := row.Scan(&user_id)
	return user_id, err
}

const getFriendRequestCount = `-- name: GetFriendRequestCount :one
SELECT COUNT(*) AS count
FROM friend_requests
WHERE (from_user = ? AND status = 'pending') OR (to_user = ? AND status = 'pending')
`

type GetFriendRequestCountParams struct {
	FromUser sql.NullString
	ToUser   sql.NullString
}

func (q *Queries) GetFriendRequestCount(ctx context.Context, arg GetFriendRequestCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFriendRequestCount, arg.FromUser, arg.ToUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFriendRequestInfo = `-- name: GetFriendRequestInfo :one
SELECT id, from_user, to_user, status, created_at, updated_at 
FROM friend_requests
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFriendRequestInfo(ctx context.Context, id string) (FriendRequest, error) {
	row := q.db.QueryRowContext(ctx, getFriendRequestInfo, id)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.FromUser,
		&i.ToUser,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendRequestUserReceive = `-- name: GetFriendRequestUserReceive :many
SELECT
    id,
    from_user,
    status,
    created_at
FROM friend_requests
WHERE to_user = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetFriendRequestUserReceiveParams struct {
	ToUser sql.NullString
	Limit  int32
	Offset int32
}

type GetFriendRequestUserReceiveRow struct {
	ID        string
	FromUser  sql.NullString
	Status    sql.NullString
	CreatedAt sql.NullTime
}

func (q *Queries) GetFriendRequestUserReceive(ctx context.Context, arg GetFriendRequestUserReceiveParams) ([]GetFriendRequestUserReceiveRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendRequestUserReceive, arg.ToUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendRequestUserReceiveRow
	for rows.Next() {
		var i GetFriendRequestUserReceiveRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUser,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendRequestUserSend = `-- name: GetFriendRequestUserSend :many
SELECT
    id,
    to_user,
    status,
    created_at
FROM friend_requests 
WHERE from_user = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetFriendRequestUserSendParams struct {
	FromUser sql.NullString
	Limit    int32
	Offset   int32
}

type GetFriendRequestUserSendRow struct {
	ID        string
	ToUser    sql.NullString
	Status    sql.NullString
	CreatedAt sql.NullTime
}

func (q *Queries) GetFriendRequestUserSend(ctx context.Context, arg GetFriendRequestUserSendParams) ([]GetFriendRequestUserSendRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendRequestUserSend, arg.FromUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendRequestUserSendRow
	for rows.Next() {
		var i GetFriendRequestUserSendRow
		if err := rows.Scan(
			&i.ID,
			&i.ToUser,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendUser = `-- name: GetFriendUser :many
SELECT u.user_id, u.user_nickname, u.user_email, u.user_avatar
FROM user_info u
JOIN friends f ON u.user_id = f.friend_id OR u.user_id = f.user_id
WHERE (f.user_id = ? OR f.friend_id = ?) 
AND u.user_id <> ?
LIMIT ? OFFSET ?
`

type GetFriendUserParams struct {
	UserID   sql.NullString
	FriendID sql.NullString
	UserID_2 string
	Limit    int32
	Offset   int32
}

type GetFriendUserRow struct {
	UserID       string
	UserNickname sql.NullString
	UserEmail    sql.NullString
	UserAvatar   sql.NullString
}

func (q *Queries) GetFriendUser(ctx context.Context, arg GetFriendUserParams) ([]GetFriendUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendUser,
		arg.UserID,
		arg.FriendID,
		arg.UserID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendUserRow
	for rows.Next() {
		var i GetFriendUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserNickname,
			&i.UserEmail,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFriendRequest = `-- name: InsertFriendRequest :exec
INSERT INTO friend_requests (id, from_user, to_user, status, created_at, updated_at)
VALUES (?, ?, ?, 'pending', now(), now())
`

type InsertFriendRequestParams struct {
	ID       string
	FromUser sql.NullString
	ToUser   sql.NullString
}

func (q *Queries) InsertFriendRequest(ctx context.Context, arg InsertFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertFriendRequest, arg.ID, arg.FromUser, arg.ToUser)
	return err
}

const responseFriendRequest = `-- name: ResponseFriendRequest :exec
UPDATE friend_requests
SET status = ?
WHERE id = ?
`

type ResponseFriendRequestParams struct {
	Status sql.NullString
	ID     string
}

func (q *Queries) ResponseFriendRequest(ctx context.Context, arg ResponseFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, responseFriendRequest, arg.Status, arg.ID)
	return err
}

const updateFriendRequest = `-- name: UpdateFriendRequest :exec
UPDATE friend_requests
SET status = ?
WHERE id = ?
`

type UpdateFriendRequestParams struct {
	Status sql.NullString
	ID     string
}

func (q *Queries) UpdateFriendRequest(ctx context.Context, arg UpdateFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateFriendRequest, arg.Status, arg.ID)
	return err
}
