// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_token_001.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteExpiredRefreshTokensByUserID = `-- name: DeleteExpiredRefreshTokensByUserID :exec
DELETE FROM refresh_tokens WHERE expires_at < now() AND user_id = ?
`

func (q *Queries) DeleteExpiredRefreshTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokensByUserID, userID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE id = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, id)
	return err
}

const deleteRefreshTokenByUserID = `-- name: DeleteRefreshTokenByUserID :exec
DELETE FROM refresh_tokens WHERE user_id = ?
`

func (q *Queries) DeleteRefreshTokenByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenByUserID, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT 
    id,
    refresh_token,
    user_id,
    expires_at,
    created_at
FROM refresh_tokens WHERE refresh_token = ?
`

type GetRefreshTokenRow struct {
	ID           string
	RefreshToken string
	UserID       string
	ExpiresAt    time.Time
	CreatedAt    sql.NullTime
}

func (q *Queries) GetRefreshToken(ctx context.Context, refreshToken string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, refreshToken)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT 
    id,
    refresh_token,
    user_id,
    expires_at,
    created_at
FROM refresh_tokens WHERE id = ?
`

type GetRefreshTokenByIDRow struct {
	ID           string
	RefreshToken string
	UserID       string
	ExpiresAt    time.Time
	CreatedAt    sql.NullTime
}

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id string) (GetRefreshTokenByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByID, id)
	var i GetRefreshTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByUserID = `-- name: GetRefreshTokenByUserID :many
SELECT 
    id,
    refresh_token,
    user_id,
    expires_at,
    created_at
FROM refresh_tokens WHERE user_id = ?
`

type GetRefreshTokenByUserIDRow struct {
	ID           string
	RefreshToken string
	UserID       string
	ExpiresAt    time.Time
	CreatedAt    sql.NullTime
}

func (q *Queries) GetRefreshTokenByUserID(ctx context.Context, userID string) ([]GetRefreshTokenByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getRefreshTokenByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefreshTokenByUserIDRow
	for rows.Next() {
		var i GetRefreshTokenByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RefreshToken,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (
    id,
    refresh_token,
    user_id,
    expires_at,
    created_at
) VALUES (?, ?, ?, ?, now())
`

type InsertRefreshTokenParams struct {
	ID           string
	RefreshToken string
	UserID       string
	ExpiresAt    time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.RefreshToken,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}
