all: help

help:
	@echo "Available commands:"
	@echo "  make build       Build the project"
	@echo "  make test        Run tests"
	@echo "  make run         Run the server"
	@echo "  make help        Show this help message"

run:
	go run cmd/server/main.go